import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Heads from "./header";
import Foots from "./footer";
import Sec1 from "./section-1";
import Sec2 from "./Section-2";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Heads />
        {children}
        <Sec1 />
        <Sec2 />
        <Foots />
      </body>
    </html>
  );
}
